<?php
/**
 * The header for our theme.
 *
 * Displays all of the <head> section and everything up till <div id="content">
 *
 * @package Tesseract
 */
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">

<?php wp_head(); ?>

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://cdn.rawgit.com/alertifyjs/alertify.js/v1.0.6/dist/js/alertify.js"><script>
<script type="text/javascript">
$(function() {
    var availableCourses = [
            "Bachelor of Agriculture",
      "Bachelor of Arts",
      "Bachelor of Biomedicine",
      "Bachelor of Commerce",
      "Bachelor of Science",
      "Bachelor of Engineering",
      "Bachelor of Fine Art",
      "Bachelor of Environments",
      "Bachelor of Music",
      "Master of Accounting",
      "Master of Actuarial Science",
      "Master of Adolescent Health & Welfare",
      "Master of Adolescent Health & Wellbeing",
      "Master of Advanced Nursing",
      "Master of Advanced Nursing Practice",
      "Master of Advanced Social Work",
      "Master of Ageing",
      "Master of Agribusiness",
      "Master of Agricultural Science",
      "Master of Agricultural Sciences",
      "Master of Agriculture",
      "Master of Animal Science",
      "Master of Applied Finance",
      "Master of Applied Linguistics",
      "Master of Applied Positive Psychology",
      "Master of Applied Science",
      "Master of Architecture",
      "Master of Architecture -",
      "Master of Art Curatorship",
      "Master of Arts",
      "Master of Arts and Community Practice",
      "Master of Arts and Cultural Management",
      "Master of Arts in Anthropology",
      "Master of Arts in Australian Studies(Thesis)",
      "Master of Arts in Classics and Archaeology",
      "Master of Arts in Criminology",
      "Master of Arts in Development Studies(Thesis only)",
      "Master of Arts in English Language and Literature",
      "Master of Arts in Fine Arts",
      "Master of Arts in Geography",
      "Master of Arts in Germanic Studies",
      "Master of Arts in History",
      "Master of Arts in History and Philosophy of Science",
      "Master of Arts in Linguistics",
      "Master of Arts in Philosophy",
      "Master of Arts in Philosophy(Adv Seminars and Shorter Thesis)(CAPPE)",
      "Master of Arts in Political Science",
      "Master of Arts in Psychology",
      "Master of Arts in Social Theory",
      "Master of Assessment and Evaluation",
      "Master of Assessment and Evaluation(Stream 150)Coursework & Major Thesis",
      "Master of Assessment and Evaluation(Stream 1A)",
      "Master of Avian Health & Medicine",
      "Master of Banking and Finance Law",
      "Master of Biomedical Engineering",
      "Master of Biomedical Science",
      "Master of Biostatistics",
      "Master of Biotechnology",
      "Master of Building",
      "Master of Building Science",
      "Master of Business Administration",
      "Master of Business Administration/Master of Information Systems",
      "Master of Business Administration/Master of Marketing",
      "Master of Business Analytics",
      "Master of Business and Information Technology",
      "Master of Choreography",
      "Master of Clinical Audiology",
      "Master of Clinical Education",
      "Master of Clinical Optometry",
      "Master of Clinical Research",
      "Master of Clinical Teaching",
      "Master of Clinical Ultrasound",
      "Master of Commerce",
      "Master of Commercial Law",
      "Master of Community Cultural Development",
      "Master of Competition and Consumer Law",
      "Master of Computer Science",
      "Master of Construction Law",
      "Master of Construction Management",
      "Master of Contemporary Art",
      "Master of Creative Arts",
      "Master of Creative Writing, Publishing and Editing",
      "Master of Criminology",
      "Master of Cultural Materials Conservation",
      "Master of Dance",
      "Master of Dental Science",
      "Master of Design",
      "Master of Design for Performance",
      "Master of Development Studies",
      "Master of Directing for Performance",
      "Master of Dramatic Art",
      "Master of Dramaturgy",
      "Master of Early Childhood Studies",
      "Master of Economics",
      "Master of Education",
      "Master of Education Policy",
      "Master of Educational Psychology",
      "Master of Educational Psychology/Doctor of Philosophy",
      "Master of Employment and Labour Relations Law",
      "Master of Energy Systems",
      "Master of Energy and Resources Law",
      "Master of Engineering",
      "Master of Engineering Management",
      "Master of Engineering Project Management",
      "Master of Engineering Science",
      "Master of Engineering Structures",
      "Master of English in a Global Context",
      "Master of Enterprise",
      "Master of Entrepreneurship",
      "Master of Environment",
      "Master of Environmental Engineering",
      "Master of Environmental Law",
      "Master of Environmental Studies",
      "Master of Epidemiology",
      "Master of Evaluation",
      "Master of Film and Television",
      "Master of Finance",
      "Master of Fine Art",
      "Master of Fine Arts",
      "Master of Food Science",
      "Master of Food Technology",
      "Master of Food and Packaging Innovation",
      "Master of Forest Ecosystem Science",
      "Master of Forest Science",
      "Master of Genetic Counselling",
      "Master of Geographic Information Technology",
      "Master of Geomatic Engineering",
      "Master of Geomatic Science",
      "Master of Geoscience",
      "Master of Global Media Communication",
      "Master of Global Studies in Education",
      "Master of Gynaecology and Obstetrics",
      "Master of Health Sciences",
      "Master of Health Social Sciences",
      "Master of Health and Medical Law",
      "Master of Horticultural Science",
      "Master of Horticulture",
      "Master of Human Resource Management",
      "Master of Human Rights Law",
      "Master of Information Systems",
      "Master of Information Systems/Graduate Diploma in Business Admin",
      "Master of Information Technology",
      "Master of Information Technology in Education(Stream 1A)",
      "Master of Instructional Leadership",
      "Master of Intellectual Property Law",
      "Master of International Business",
      "Master of International Development",
      "Master of International Relations",
      "Master of International Tax",
      "Master of Islamic Studies",
      "Master of Journalism",
      "Master of Landscape Architecture",
      "Master of Law and Development",
      "Master of Laws",
      "Master of Learning Intervention",
      "Master of Legal Systems",
      "Master of Literacy",
      "Master of Management",
      "Master of Marketing",
      "Master of Marketing Communications",
      "Master of Medicine",
      "Master of Mental Health Science",
      "Master of Modern Languages Education",
      "Master of Modern Languages Education(Stream 100A) Coursework and ThesisA",
      "Master of Modern Languages Education(Stream 1A)",
      "Master of Music",
      "Master of Music Performance(VCA)",
      "Master of Music Studies",
      "Master of Music Therapy",
      "Master of Nanoelectronic Engineering",
      "Master of Narrative Therapy and Community Work",
      "Master of Numeracy",
      "Master of Nursing",
      "Master of Nursing Science",
      "Master of Operations Research and Management Science",
      "Master of Philosophy",
      "Master of Philosophy - MDHS",
      "Master of Physiotherapy",
      "Master of Planning & Design(Facility Planning & Management) by Research",
      "Master of Planning and Design",
      "Master of Primary Health Care",
      "Master of Private Law",
      "Master of Producing",
      "Master of Production Design for Screen",
      "Master of Property",
      "Master of Psychiatry",
      "Master of Psychology",
      "Master of Public Administration",
      "Master of Public Health",
      "Master of Public Policy and Management",
      "Master of Public and International Law",
      "Master of Publishing and Communications",
      "Master of Rehabilitation Science",
      "Master of Research",
      "Master of Science",
      "Master of Science - Information Systems",
      "Master of Science - Medicine",
      "Master of Science-Pharmacology",
      "Master of Screenwriting",
      "Master of Social Health",
      "Master of Social Policy",
      "Master of Social Work",
      "Master of Software Systems Engineering",
      "Master of Spatial Information Science",
      "Master of Speech Pathology",
      "Master of Sports Medicine",
      "Master of Supply Chain Management",
      "Master of Surgery",
      "Master of Surgical Education",
      "Master of Surveying",
      "Master of Surveying Science",
      "Master of TESOL",
      "Master of Tax",
      "Master of Teaching",
      "Master of Telecommunications Engineering",
      "Master of Tertiary Education Management",
      "Master of Town & Regional Planning",
      "Master of Translation",
      "Master of Transnational Arts",
      "Master of Urban Design",
      "Master of Urban Horticulture",
      "Master of Urban Planning",
      "Master of Urban and Cultural Heritage",
      "Master of Veterinary Public Health",
      "Master of Veterinary Science",
      "Master of Veterinary Studies",
      "Master of Wine Technology and Viticulture",
      "Master of Wood Science",
      "Master of Writing for Performance",
      "Master of Youth Mental Health",
      "Master of Architecture Studio A",
      "Master of Architecture Studio B",
      "Master of Architecture Studio C",
      "Master of Architecture Studio D",
      "Master of Architecture Studio E",
      "Graduate Certificate in Adolescent Health and Wellbeing",
      "Graduate Certificate in Advanced Learning and Leadership",
      "Graduate Certificate in Ageing",
      "Graduate Certificate in Agribusiness",
      "Graduate Certificate in Agricultural Sciences",
      "Graduate Certificate in Arboriculture",
      "Graduate Certificate in Arts",
      "Graduate Certificate in Arts and Community Engagement",
      "Graduate Certificate in Avian Health",
      "Graduate Certificate in Biostatistics",
      "Graduate Certificate in Bushfire Planning and Management",
      "Graduate Certificate in Business Forensics",
      "Graduate Certificate in Cancer Sciences",
      "Graduate Certificate in Catchment and Waterway Management",
      "Graduate Certificate in Climate Change for Primary Industries",
      "Graduate Certificate in Clinical Research",
      "Graduate Certificate in Clinical Teaching",
      "Graduate Certificate in Clinical Ultrasound",
      "Graduate Certificate in Communication and Customer Strategy",
      "Graduate Certificate in Dental Therapy",
      "Graduate Certificate in Early Literacy Intervention",
      "Graduate Certificate in Education",
      "Graduate Certificate in Educational Research",
      "Graduate Certificate in Environment",
      "Graduate Certificate in Evaluation",
      "Graduate Certificate in Food Science",
      "Graduate Certificate in Forest Systems Management",
      "Graduate Certificate in Garden Design",
      "Graduate Certificate in Global Wine Studies",
      "Graduate Certificate in Indigenous Arts Management",
      "Graduate Certificate in Indigenous Research and Leadership",
      "Graduate Certificate in Journalism",
      "Graduate Certificate in Learning Intervention",
      "Graduate Certificate in Marketing",
      "Graduate Certificate in Marketing Management",
      "Graduate Certificate in Mental Health Science",
      "Graduate Certificate in Modern Languages Education",
      "Graduate Certificate in Music",
      "Graduate Certificate in Nursing Practice",
      "Graduate Certificate in Palliative Care",
      "Graduate Certificate in Physiotherapy",
      "Graduate Certificate in Primary Care Nursing",
      "Graduate Certificate in Publishing and Communications",
      "Graduate Certificate in Quality Assurance",
      "Graduate Certificate in Rehabilitation Science",
      "Graduate Certificate in Research Management and Policy",
      "Graduate Certificate in Science",
      "Graduate Certificate in Sexual Health",
      "Graduate Certificate in Small Animal Emergency and Critical Care",
      "Graduate Certificate in Small Animal Ultrasound Abdominal",
      "Graduate Certificate in Social Impact",
      "Graduate Certificate in Surgical Education",
      "Graduate Certificate in TESOL",
      "Graduate Certificate in Tertiary Education Management",
      "Graduate Certificate in Tertiary Teaching",
      "Graduate Certificate in Transfusion Practice",
      "Graduate Certificate in University Management",
      "Graduate Certificate in University Teaching",
      "Graduate Certificate in Urban and Cultural Heritage",
      "Graduate Certificate in Visual Art",
      "Graduate Certificate in Voice Studies",
      "Graduate Certificate in Wine Technology and Viticulture",
      "Graduate Certificate in Youth Mental Health",
      "Graduate Certificate in the Teaching of Shakespeare",
      "Graduate Diploma in Actuarial Science",
      "Graduate Diploma in Adolescent Health and Welfare",
      "Graduate Diploma in Adolescent Health and Wellbeing",
      "Graduate Diploma in Ageing",
      "Graduate Diploma in Agribusiness for Veterinarians",
      "Graduate Diploma in Agricultural Sciences",
      "Graduate Diploma in Animal Science",
      "Graduate Diploma in Arts",
      "Graduate Diploma in Arts and Cultural Management",
      "Graduate Diploma in Asian Law",
      "Graduate Diploma in Banking and Finance Law",
      "Graduate Diploma in Biostatistics",
      "Graduate Diploma in Built Environments",
      "Graduate Diploma in Bushfire Planning and Management",
      "Graduate Diploma in Business Administration",
      "Graduate Diploma in Clinical Dentistry",
      "Graduate Diploma in Clinical Education",
      "Graduate Diploma in Clinical Research",
      "Graduate Diploma in Clinical Ultrasound",
      "Graduate Diploma in Communications Law",
      "Graduate Diploma in Competition Law",
      "Graduate Diploma in Competition and Consumer Law",
      "Graduate Diploma in Construction Law",
      "Graduate Diploma in Corporations and Securities Law",
      "Graduate Diploma in Dispute Resolution",
      "Graduate Diploma in Economics",
      "Graduate Diploma in Employment and Labour Relations Law",
      "Graduate Diploma in Energy and Resources Law",
      "Graduate Diploma in Environment",
      "Graduate Diploma in Environmental Law",
      "Graduate Diploma in Finance",
      "Graduate Diploma in Food Science",
      "Graduate Diploma in Forest Systems Management",
      "Graduate Diploma in Genetic Counselling",
      "Graduate Diploma in Government Law",
      "Graduate Diploma in Guided Imagery and Music",
      "Graduate Diploma in Health and Medical Law",
      "Graduate Diploma in Human Rights Law",
      "Graduate Diploma in Intellectual Property Law",
      "Graduate Diploma in International Economic Law",
      "Graduate Diploma in International Law",
      "Graduate Diploma in International Tax",
      "Graduate Diploma in Journalism",
      "Graduate Diploma in Legal Studies",
      "Graduate Diploma in Marketing",
      "Graduate Diploma in Mental Health Science",
      "Graduate Diploma in Music",
      "Graduate Diploma in Nursing Practice",
      "Graduate Diploma in Performance Creation",
      "Graduate Diploma in Primary Care Nursing",
      "Graduate Diploma in Professional Accounting",
      "Graduate Diploma in Property Valuation",
      "Graduate Diploma in Psychology",
      "Graduate Diploma in Publishing and Communications",
      "Graduate Diploma in Rehabilitation Science",
      "Graduate Diploma in Science",
      "Graduate Diploma in Sports Law",
      "Graduate Diploma in Surgical Anatomy",
      "Graduate Diploma in Surgical Education",
      "Graduate Diploma in Tax",
      "Graduate Diploma in Tropical Medicine and Hygiene",
      "Graduate Diploma in Urban Horticulture",
      "Graduate Diploma in Veterinary Professional Leadership and Management",
      "Graduate Diploma in Voice Studies",
      "Graduate Diploma in Youth Mental Health",
      "Doctor of Agricultural Science",
      "Doctor of Clinical Dentistry",
      "Doctor of Clinical Physiotherapy",
      "Doctor of Dental Science",
      "Doctor of Dental Surgery",
      "Doctor of Education",
      "Doctor of Forest Science",
      "Doctor of Juridical Science",
      "Doctor of Laws",
      "Doctor of Medical Science",
      "Doctor of Medicine",
      "Doctor of Music",
      "Doctor of Optometry",
      "Doctor of Philosophy",
      "Doctor of Physiotherapy",
      "Doctor of Psychology",
      "Doctor of Science",
      "Doctor of Veterinary Medicine",
      "Doctor of Veterinary Science",
      "Doctor of Visual and Performing Arts",
      "Doctor of Education Thesis Proposal",
      "Ph.D.- Architecture & Planning",
      "Ph.D.- Arts",
      "Ph.D.- Dental Science",
      "Ph.D.- Education",
      "Ph.D.- Engineering",
      "Ph.D.- Law",
      "Ph.D.- Medicine, Dentistry & Health Sciences",
      "Ph.D.- Music",
      "Ph.D.- Science",
      "Ph.D.- Veterinary Science",
      "Ph.D.- Accounting Thesis Workshop",
      "Postgraduate Certificate in Arts",
      "Postgraduate Certificate in Biostatistics",
      "Postgraduate Certificate in Bushfire Planning and Management",
      "Postgraduate Certificate in Climate Change for Primary Industries",
      "Postgraduate Certificate in Clinical Ultrasound",
      "Postgraduate Certificate in Dental Therapy",
      "Postgraduate Certificate in Education",
      "Postgraduate Certificate in Educational Research",
      "Postgraduate Certificate in Environment",
      "Postgraduate Certificate in Evaluation",
      "Postgraduate Certificate in Modern Languages Education",
      "Postgraduate Certificate in Nursing Practice",
      "Postgraduate Certificate in Physiotherapy",
      "Postgraduate Certificate in Primary Care Nursing",
      "Postgraduate Certificate in Professional Ethics",
      "Postgraduate Certificate in TESOL",
      "Postgraduate Certificate in Veterinary Public Health",
      "Postgraduate Certificate in Voice Studies",
      "Postgraduate Certificate in the Teaching of Shakespeare",
      "Postgraduate Diploma in Agricultural Science",
      "Postgraduate Diploma in Arts",
      "Postgraduate Diploma in Arts and Cultural Management",
      "Postgraduate Diploma in Biostatistics",
      "Postgraduate Diploma in Bushfire Planning and Management",
      "Postgraduate Diploma in Clinical Dentistry",
      "Postgraduate Diploma in Clinical Ultrasound",
      "Postgraduate Diploma in Environment",
      "Postgraduate Diploma in Food Science",
      "Postgraduate Diploma in Management",
      "Postgraduate Diploma in Nursing",
      "Postgraduate Diploma in Nursing Practice",
      "Postgraduate Diploma in Primary Care Nursing",
      "Postgraduate Diploma in Professional Ethics",
      "Postgraduate Diploma in Psychology",
      "Postgraduate Diploma in Science",
      "Postgraduate Diploma in Surgical Anatomy",
      "Postgraduate Diploma in Veterinary Public Health",
      "Postgraduate Diploma in Voice Studies",
      "Professional Certificate in Arts Education",
      "Professional Certificate in Chinese Language Teaching",
      "Professional Certificate in Clinical Research",
      "Professional Certificate in Education",
      "Professional Certificate in Global Wine Studies",
      "Professional Certificate in History Education",
      "Professional Certificate in Indigenous Research",
      "Professional Certificate in Instructional Leadership",
      "Professional Certificate in Mathematics Education",
      "Professional Certificate in Mental Health Practice",
      "Professional Certificate in Positive Psychology",
      "Professional Certificate in Teaching",
      "Specialist Certificate in Ageing",
      "Specialist Certificate in Anterior and Dry Eye Disorders",
      "Specialist Certificate in Chinese Language Teaching",
      "Specialist Certificate in Clinical Research",
      "Specialist Certificate in Clinical Research-Clinical Trials Coordination",
      "Specialist Certificate in Clinical Research-Clinical Trials Monitoring",
      "Specialist Certificate in Criminology",
      "Specialist Certificate in Cross-Cultural Conservation and Heritage",
      "Specialist Certificate in Economic Design",
      "Specialist Certificate in Executive Leadership",
      "Specialist Certificate in Glaucoma and Retinal Disease",
      "Specialist Certificate in Green Roofs and Walls",
      "Specialist Certificate in Hearing Science",
      "Specialist Certificate in Paediatric Orthopaedic Physiotherapy",
      "Specialist Certificate in Palliative Care",
      "Specialist Certificate in Practice of Tropical Medicine and Hygiene",
      "Specialist Certificate in Rehabilitation Science",
      "Specialist Certificate in Rural Paediatric Practice",
      "Specialist Certificate in Strategic Communications and Engagement",
      "Specialist Certificate in Strategic Marketing",
      "Specialist Certificate in Teaching for Graduate Researchers",
      "Specialist Certificate in Travel Medicine",
      "Specialist Certificate in Urban and Cultural Heritage",
      "Specialist Certificate in the Management of Contact Lens Patients",
      "Specialist Certificate in the Management of Low Vision Patients",
      "Specialist Certificate in the Management of Neural-Ophthalmic Disorders",
      "Specialist Certificate in the Management of Paediatric Patients"
    ];
    var availableMajors = [
            "Production Animal Science",
      "Plant and Soil Science",
      "Agricultural Economics",
      "Ancient World Studies",
      "Anthropology",
      "Arabic",
      "Art History",
      "Asian Studies",
      "Australian Indigenous Studies",
      "Chinese language",
      "Classics",
      "Creative Writing",
      "Criminology",
      "Economics",
      "English and theatre studies",
      "French",
      "Gender studies",
      "Geography",
      "German",
      "Hebrew and Jewish studies",
      "History",
      "History and philosophy of science",
      "Indonesian studies",
      "Islamic studies",
      "Italian",
      "Japanese",
      "Linguistics and applied linguistics",
      "Media and communications",
      "Philosophy",
      "Politics and international studies",
      "Psychology",
      "Russian",
      "Screen and cultural studies",
      "Sociology",
      "Spanish and Latin American studies",
      "Latin American studies",
      "Biochemistry and molecular biology",
      "Bioengineering systems",
      "Biotechnology",
      "Cell and development biology",
      "Defence & disease",
      "Genetics",
      "Health information",
      "Human structure and function",
      "Immunology",
      "Microbiology and immunology",
      "Neuroscience",
      "Pathology",
      "Pharmacology",
      "Physiology ",
      "Accounting",
      "Actuarial studies",
      "Business",
      "Economics",
      "Finance",
      "Management",
      "Marketing",
      "Agricultural science",
      "Animal health and disease",
      "Animal science and management",
      "Biochemistry and molecular biology",
      "Bioengineering systems",
      "Biotechnology",
      "Cell and development biology",
      "Chemical systems",
      "Chemistry",
      "Computational biology",
      "Computing and software systems",
      "Climate and weather",
      "Civil systems",
      "Ecology and evolutionary biology",
      "Electrical systems",
      "Environmental science",
      "Food science",
      "Forest science",
      "Genetics",
      "Geography",
      "Geology",
      "Human structure and function",
      "Immunology",
      "Informatics",
      "Marine biology",
      "Mathematical physics",
      "Mathematics and statistics",
      "Mechanical systems",
      "Mechatronics systems",
      "Microbiology and immunology",
      "Neuroscience",
      "Pathology",
      "Pharmacology",
      "Physics",
      "Physiology",
      "Plant science",
      "Psychology",
      "Spatial systems",
      "Zoology",
      "Chemical and biomolecular engineering",
      "Chemical engineering",
      "Electrical engineering",
      "Mechanical engineering",
      "Software engineering",
      "Civil engineering",
      "Animation",
      "Contemporary music",
      "Dance",
      "Film and television",
      "Music theatre",
      "Production",
      "Screenwriting",
      "Theatre practice",
      "Visual art",
      "Architecture",
      "Construction",
      "Engineering systems",
      "Environmental geographies",
      "Environmental science",
      "Landscape architecture",
      "Landscape management",
      "Property",
      "Spatial systems",
      "Urban design and planning",
      "Performance/composition/musicology/ethnomusicology",
      "Jazz & improvisation",
      "Interactive composition",
      "Cancer Nursing",
      "Critical Care",
      "Emergency Care",
      "Mental Health",
      "Neonatal Intensive Care",
      "Nurse Practitioner",
      "Paediatrics",
      "Palliative Care",
      "Rural Critical Care",
      "Research",
      "Coursework",
      "Agriculture",
      "Civil",
      "Computer",
      "Geographic Information Systems",
      "Geomatics",
      "Horticulture",
      "Surveying",
      "Thesis",
      "Design",
      "Advanced Seminar & Shorter Thesis",
      "Art History)(Thesis",
      "Australian Indigenous Studies",
      "Creative Writing",
      "Cultural Material Conservation",
      "Policy Studies)(Advanced Seminars & Shorter Thesis",
      "Professional and Applied Ethics",
      "Screen Studies",
      "Sociology) by Researc",
      "Theatre Studies",
      "Thesis only",
      "Advanced Seminars and Shorter Thesis",
      "Stream 100A) Coursework and Thesis",
      "Executive",
      "Professional",
      "VCA",
      "Accounting",
      "Actuarial Science",
      "Employee Relations and Human Resource Management",
      "Finance",
      "Management",
      "Marketing",
      "Computing",
      "Clinical-Thesis",
      "Para Clinical-Thesis",
      "Urban Design",
      "Gender & Development",
      "Direction",
      "By Publication",
      "CLIL",
      "Educational Management",
      "International Baccalaureate",
      "International Baccalaureate) D",
      "International Baccalaureate) PY",
      "Language Intervention and Hearing Impairment",
      "Special Education Inclusion and Early Intervention",
      "Special Education, Inclusion & Early Intervention",
      "Specific Learning Difficulties",
      "Stream 1",
      "Stream 100) Major Thesi",
      "Stream 100A) Coursework and Thesis ",
      "Stream 1A",
      "Stream 2",
      "Student Wellbeing",
      "Three Strand",
      "International",
      "C.I.T.R.I. Thesis",
      "Chemical",
      "Electrical and Electronic",
      "Environmental Research",
      "Mechanical and Manufacturing",
      "Science",
      "Community Cultural Development",
      "Contemporary Music",
      "Dance",
      "Film and Television",
      "Interdisciplinary Arts Practice",
      "Music Theatre",
      "Production",
      "Theatre",
      "Visual Art",
      "Transcultural Mental Health",
      "Accounting and Finance",
      "Human Resources",
      "Radiology",
      "Stream A",
      "Stream B",
      "Composition",
      "Interactive Composition",
      "Jazz & Improvisation",
      "Music Performance",
      "Music Psychology & Performance Science",
      "Music Therapy",
      "Musicology/Ethnomusicology",
      "Opera Performance",
      "Performance Teaching",
      "Agricultural Sciences",
      "Architecture, Building and Planning",
      "Arts",
      "Education",
      "Engineering",
      "Land and Environment",
      "Law",
      "Behavioural Science",
      "Biomedical Science",
      "Dental Science",
      "Health Sciences",
      "Medicine",
      "Nursing",
      "Physiotherapy",
      "Population Health",
      "Population and Global Health",
      "Psychological Sciences",
      "Social Work",
      "Music",
      "Veterinary Science",
      "Victorian College of the Arts",
      "Musculoskeletal Physiotherapy",
      "Clinical - Singapore",
      "Clinical Child Psychology)/Doctor of Philosoph",
      "Clinical Neuropsychology",
      "Clinical Neuropsychology)/Doctor of Philosoph",
      "Clinical Psychology",
      "Clinical Psychology)/Doctor of Philosoph",
      "Organisational/Industrial Psychology)/Ph",
      "Enhanced",
      "Ballarat University College)-Human Movement&Sport Sc",
      "BioSciences",
      "Bioinformatics",
      "Biomedical and Health Sciences",
      "Botany",
      "Chemistry",
      "Computer Science",
      "Earth Sciences",
      "Ecosystem Science",
      "Epidemiology",
      "Forestry",
      "Genetics",
      "Geography",
      "History and Philosophy of Science",
      "Information Systems",
      "Mathematics and Statistics",
      "Optometry",
      "Pathology",
      "Physics",
      "Physiology",
      "Vision Science",
      "Zoology",
      "Austin) -Thesi",
      "Early Childhood",
      "Early Years",
      "Primary",
      "Secondary",
      "Secondary) Internshi",
      "Teach for Australia",
      "Extended",
      "Emergency Animal Diseases",
      "Advanced",
      "Uni Georgia",
      "Advanced Clinical Practice",
      "Middle Years Literacies",
      "Practical Music",
      "Cancer and Palliative Care",
      "Emergency",
      "Paediatric Intensive Care",
      "Exercise and Women's Health",
      "Pelvic Floor Physiotherapy",
      "Business and Economics",
      "Medicine, Dentistry and Health Sciences",
      "Editing and Communications",
      "Generalist",
      "LI&HI",
      "SE,I&EI",
      "EAD",
      "Mental Health Theory",
      "Autism Spectrum Conditions",
      "Positive Behaviour and Learning",
      "Positive Education",
      "TFA Mentoring",
      "Years 11-12",
      "Years 7-10",
      "Clinical",
      "Biomedical Research Mgmt",
      "Neuroscience",
      "Oncology",
      "Forensic Disability",
      "Sexual Offender Management"
    ];
    $( "#course" ).autocomplete({
        source: function(request, response) {
           var results = $.ui.autocomplete.filter(availableCourses, request.term);
           response(results.slice(0, 5));
        }
    });
    $( "#major" ).autocomplete({
        source: function(request, response) {
           var results = $.ui.autocomplete.filter(availableMajors, request.term);
           response(results.slice(0, 5));
        }
    });
});
var submitted=false;
function popup(){
    alertify.delay(3000);
    alertify.success("Successful signup! Follow us on Facebook and Linkedin!");
}
</script>

</head>

<?php // Additional body classes
$bodyClass = ( version_compare($wp_version, '4.0.0', '>') && is_customize_preview() ) ? 'backend' : 'frontend';
if ( (is_page()) && (has_post_thumbnail()) ) $bodyClass .= ' tesseract-featured';

$opValue = get_theme_mod('tesseract_tho_header_colors_bck_color_opacity');	
$header_bckOpacity = is_numeric($opValue) ? TRUE : FALSE;	
if ( is_front_page() && ( $header_bckOpacity && ( intval($opValue) < 100 ) ) ) $bodyClass .= ' transparent-header';	?>

<body <?php body_class( $bodyClass ); ?>>

<nav id="mobile-navigation" class="top-navigation" role="navigation">

	<?php $anyMenu = get_terms( 'nav_menu' ) ? true : false;
    	  $menuSelect = get_theme_mod('tesseract_tho_header_menu_select');
                    
		if ( $anyMenu && ( ( $menuSelect ) && ( $menuSelect !== 'none' ) ) ) : 	
			wp_nav_menu( array( 'menu' => $menuSelect, 'container_class' => 'header-menu' ) );               		
		elseif ( $anyMenu && ( !$menuSelect || ( $menuSelect == 'none' ) ) ) :
			$menu = get_terms( 'nav_menu' ); 
			$menu_id = $menu[0]->term_id;						
			wp_nav_menu( array( 'menu_id' => $menu_id ) );
		elseif ( !$anyMenu ) :
			wp_nav_menu( array( 'theme_location' => 'primary', 'menu_class' => 'nav-menu' ) );                        
		endif; ?>

</nav><!-- #site-navigation -->  	

<div id="page" class="hfeed site">
	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'tesseract' ); ?></a>
    
    <a class="menu-open dashicons dashicons-menu" href="#mobile-navigation"></a>
    <a class="menu-close dashicons dashicons-no" href="#"></a>            
    

	<header id="masthead" class="site-header <?php echo get_header_image() ? 'is-header-image' : 'no-header-image'; ?>" role="banner">
    
    <?php $logoImg = get_theme_mod('tesseract_logo_image'); 
	$blogname = get_bloginfo('blogname'); 
	$headright_content = get_theme_mod('tesseract_tho_header_content_content');
	$headright_content_default_button = get_theme_mod('tesseract_tho_header_content_if_button');
	
	if ( !$logoImg && $blogname ) $brand_content = 'blogname';
	if ( $logoImg ) $brand_content = 'logo';
	if ( !$logoImg && !$blogname ) $brand_content = 'no-brand'; 

	?>
    
        <div id="site-banner" class="cf<?php echo ' ' . $headright_content . ' ' . $brand_content; echo ( ( $headright_content  ) && ( $headright_content !== 'nothing' ) ) ?  ' is-right' : ' no-right'; ?>">               
            
            <div id="site-banner-left" class="<?php echo ( ( $headright_content  ) && ( $headright_content !== 'nothing' ) ) ?  'is-right' : 'no-right'; ?>">
				
                <?php if ( $logoImg || $blogname ) { ?>
                    <div class="site-branding">
                        <?php if ( $logoImg ) : ?>
                            <h1 class="site-logo"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><img src="<?php echo $logoImg; ?>" alt="logo" /></a></h1>
                        <?php else : ?>
                            <h1 class="site-title"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a></h1>
                        <?php endif; ?>
                    </div><!-- .site-branding -->
              	<?php } ?>
				
                <nav id="site-navigation" class="main-navigation top-navigation" role="navigation">
                	
					<?php $anyMenu = get_terms( 'nav_menu' ) ? true : false;
                          $menuSelect = get_theme_mod('tesseract_tho_header_menu_select');
                    
						if ( $anyMenu && ( ( $menuSelect ) && ( $menuSelect !== 'none' ) ) ) : 	
							wp_nav_menu( array( 'menu' => $menuSelect, 'container_class' => 'header-menu' ) );               		
						elseif ( $anyMenu && ( !$menuSelect || ( $menuSelect == 'none' ) ) ) :
							$menu = get_terms( 'nav_menu' ); 
							$menu_id = $menu[0]->term_id;						
							wp_nav_menu( array( 'menu_id' => $menu_id ) );
						elseif ( !$anyMenu ) :
							wp_nav_menu( array( 'theme_location' => 'primary', 'menu_class' => 'nav-menu' ) );                        
						endif; ?>

				</nav><!-- #site-navigation --> 
                
            </div>

            <?php if ( $headright_content ) : ?>            

               	<div id="site-banner-right">
			
					<?php tesseract_header_right_content($headright_content); ?>                  
                   
             	</div>
         	
			<?php elseif ( !$headright_content && $headright_content_default_button ) : ?>            

            	<div id="site-banner-right">
                
                    <div id="header-button-container">
                        <div id="header-button-container-inner">
                            <?php echo $headright_content_default_button; ?>
                        </div>
                    </div> 
                   
               </div>

            <?php else : ?>
			
				<div id="site-banner-right">
                
                	<div id="header-button-container">
                    	<div id="header-button-container-inner">
                        	<a href="/" class="button primary-button">Primary Button</a>
                    		<a href="/" class="button secondary-button">Secondary Button</a>
                		</div>
                   	</div>
                </div>				
			
			<?php endif; ?>

        </div>            
        
	</header><!-- #masthead -->
    
    <div id="content" class="cf site-content">